---
title: "Test functional analysis on GEO dataset collection"
author:
  - name: Paolo Angelino
    affiliation:
      - TDS Facility, SIB Swiss Institute of Bioinformatics, Lausanne, Switzerland
    email: paolo.angelino@sib.swiss
date: "`r format(Sys.time(), '%d %b %Y')`"
output:
  prettydoc::html_pretty:
    theme: hpstr
    toc: yes
    toc_depth: 2
    number_sections: yes
    fig_caption: yes
    df_print: paged
---

```{r}
library(ReactomePA)
library(clusterProfiler)
require(dplyr)
library(ggplot2)
library(stringr)
```

```{r}
# CRT.extrR.markers <- readRDS("/data/pangelin/HUG/Thibaud/RC_GEOMX/data/CRT.extrR.markers.rds")
# gene.symbol <- CRT.extrR.markers$Symbol
gene.list =  "de_intersect_plus_bulk_genes"  # "de_intersect" DE4" "DEall" "meta_intersect_unionDE"  "5k" "meta"
# gene.symbol = readRDS(file = "/data/pangelin/HUG/Thibaud/RC_GEOMX/analysis/results/de_intersect_genes.rds")
keep <- readRDS("/data/pangelin/HUG/Thibaud/RC_GEOMX/analysis/results/gene_lists.rds")
gene.symbol <- keep[[gene.list]]
```


```{r}
ens2annot <- clusterProfiler::bitr(
    geneID = gene.symbol, 
    fromType = "SYMBOL", 
    toType = c("ENTREZID", "ENSEMBL"), 
    OrgDb = "org.Hs.eg.db", 
    drop = FALSE
  ) %>% 
    distinct(SYMBOL, .keep_all = TRUE) %>%     # Heuristic to remove duplicated entrez ids.
    as_tibble()

ens2annot <- ens2annot[!is.na(ens2annot$ENTREZID),]
```

## ORA

```{r}
x <- enrichPathway(gene=ens2annot$ENTREZID, pvalueCutoff = 0.05, readable=TRUE)
head(x)
```

```{r}
require(msigdbr)
m_t2g <- msigdbr(species = "Homo sapiens", category = "H") %>% 
  dplyr::select(gs_name, entrez_gene)
```

```{r}
em <- enricher(ens2annot$ENTREZID, TERM2GENE=m_t2g)
head(em)
```

## GSEA

```{r}
DE_4datasets_scaled <- readRDS("/data/pangelin/HUG/Thibaud/RC_GEOMX/analysis/results/DE_4datasets_scaled.rds")[[1]]
DE_alldatasets_scaled <- readRDS("/data/pangelin/HUG/Thibaud/RC_GEOMX/analysis/results/DE_alldatasets_scaled.rds")[[1]]
DE_bulk_scaled <- readRDS("/data/pangelin/HUG/Thibaud/RC_GEOMX/analysis/results/DE_bulkDatasets_scaled.rds")[[1]]
merge_DE <- merge(DE_4datasets_scaled,DE_bulk_scaled, by=0)
rownames(merge_DE) <- merge_DE$Row.names
merge_DE$Pval <- pmin(merge_DE$P.Value.x, merge_DE$P.Value.y)
merge_DE <- merge(merge_DE, DE_alldatasets_scaled, by=0)
merge_DE$Pval <- pmax(merge_DE$Pval,merge_DE$P.Value)
length(which(merge_DE$Pval < 0.05))

ens2annot <- clusterProfiler::bitr(
    geneID = merge_DE$Row.names, 
    fromType = "SYMBOL", 
    toType = c("ENTREZID", "ENSEMBL"), 
    OrgDb = "org.Hs.eg.db", 
    drop = FALSE
  ) %>% 
    distinct(SYMBOL, .keep_all = TRUE) %>%     # Heuristic to remove duplicated entrez ids.
    as_tibble()

ens2annot <- ens2annot[!is.na(ens2annot$ENTREZID),]
ens2annot <- ens2annot[!duplicated(ens2annot$ENTREZID),]
ens2annot <- as.data.frame(ens2annot)
rownames(ens2annot) <- ens2annot$SYMBOL

res <- merge_DE[merge_DE$Row.names %in% ens2annot$SYMBOL,]
res$ENTREZID <- ens2annot[res$Row.names ,"ENTREZID"]
genelist <- -log10(res$Pval)
names(genelist) <- res$ENTREZID 
genelist <- genelist[order(genelist, decreasing = T)]
```


```{r, eval=FALSE}
meta.degs.extrR <- readRDS("/data/pangelin/HUG/Thibaud/RC_GEOMX/data/meta.degs.extrR.rds")
meta.degs.extrR@metaresult

ens2annot <- clusterProfiler::bitr(
    geneID = meta.degs.extrR@metaresult$Symbol, 
    fromType = "SYMBOL", 
    toType = c("ENTREZID", "ENSEMBL"), 
    OrgDb = "org.Hs.eg.db", 
    drop = FALSE
  ) %>% 
    distinct(SYMBOL, .keep_all = TRUE) %>%     # Heuristic to remove duplicated entrez ids.
    as_tibble()

ens2annot <- ens2annot[!is.na(ens2annot$ENTREZID),]
ens2annot <- ens2annot[!duplicated(ens2annot$ENTREZID),]
ens2annot <- as.data.frame(ens2annot)
rownames(ens2annot) <- ens2annot$SYMBOL

res <- meta.degs.extrR@metaresult[meta.degs.extrR@metaresult$Symbol %in% ens2annot$SYMBOL,]
res$ENTREZID <- ens2annot[res$Symbol ,"ENTREZID"]
genelist <- 1/res$rank
names(genelist) <- res$ENTREZID 
```

### GSEA Reactome

```{r}
y <- gsePathway(genelist, 
                pvalueCutoff = 0.05,
                pAdjustMethod = "none", 
                verbose = FALSE, scoreType = "pos")
head(y)
```

### GSEA Hallmarks

```{r}
em <- GSEA(genelist, 
                pvalueCutoff = 0.05,
                pAdjustMethod = "none",
           TERM2GENE=m_t2g, scoreType = "pos")
head(em)
```

### Plots

```{r, fig.height=6}
library(enrichplot)
gsea_out <- merge_result(list(H=em, R=y)) 
dotplot(gsea_out, showCategory=5, color="pvalue")  + scale_y_discrete(labels=function(x) str_wrap(x, width=30)) 
dotplot(em, showCategory=10, color="pvalue")  + scale_y_discrete(labels=function(x) str_wrap(x, width=30)) 
dotplot(y, showCategory=10, color="pvalue")  + scale_y_discrete(labels=function(x) str_wrap(x, width=40)) 
```

```{r, fig.width=6}
upsetplot(em)
upsetplot(y)
```
```{r, fig.width=8, fig.height=7}
ridgeplot(em, showCategory = 10)
ridgeplot(y, showCategory = 10) + scale_y_discrete(labels=function(x) str_wrap(x, width=50)) 
```

```{r}
gseaplot2(em, geneSetID = 1:3)
```


```{r}
gseaplot2(y, geneSetID = 1:3)
```

### GSEA algorithm tests

```{r}
df2 <- seq(14364, 1)
names(df2) <- names(sample(genelist))
GSEA(df2, TERM2GENE=m_t2g, scoreType = "pos")
```


```{r}
topgenes <- m_t2g[m_t2g$gs_name == "HALLMARK_ADIPOGENESIS", "entrez_gene"]
df2 <- seq(14364, 1)
names(df2) <- names(genelist)
df2[which(names(df2) %in% topgenes$entrez_gene)] <- seq(1:173)*100000
df2 <- sort(df2, decreasing = T)
GSEA(df2, TERM2GENE=m_t2g, scoreType = "pos")
```


```{r, eval=FALSE}
res <- meta.degs.extrR@metaresult[meta.degs.extrR@metaresult$Symbol %in% ens2annot$SYMBOL,]
res$ENTREZID <- ens2annot[res$Symbol ,"ENTREZID"]
genelist <- res$randomSummary
names(genelist) <- res$ENTREZID 
genelist <- sort(genelist, decreasing = T)
```

```{r, eval=FALSE}
y <- gsePathway(genelist, 
                pvalueCutoff = 0.05,
                pAdjustMethod = "BH", 
                verbose = FALSE)
head(y)
```


```{r, eval=FALSE}
em <- GSEA(genelist, TERM2GENE=m_t2g, scoreType = "pos")
head(em)
```
