---
title: "`r paste0('glmnet and randomForest in R (caret), ', params$title)`"
author: "Paolo Angelino"
output:
  html_document:
    depth: 2
    highlight: tango
    number_sections: yes
    toc: yes
params:
  usescaled: TRUE
  trainds: !r c("GSE150082", "GSE94104", "GSE133057", "GSE93375")
  testds: !r c("GSE209746", "GSE145037") # , "GSE190826",  "GSE45404_GPL1", "GSE45404_GPL2"
  allds: TRUE
  seed: 26326
  save.model: /data/pangelin/HUG/Thibaud/RC_GEOMX/analysis/results/randomSampling_modeling_extra_final_de_intersect_6datasets_scaled.rds
  gene.list: "de_intersect" # "DE4" "DEall" "meta_intersect_unionDE"  "5k" "meta"  "de_intersect_plus_bulk_genes"
  title: "random sampling, DE intersect 4 and all datasets, scaled data"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo=TRUE, message=FALSE, warning=FALSE}
if (!require("tidyverse", quietly = TRUE))
    install.packages("tidyverse")

if (!require("caret", quietly = TRUE))
    BiocManager::install("caret")

if (!require("caTools", quietly = TRUE))
    BiocManager::install("caTools")

# load libraries
library(tidyverse)
library(caret)
library(caTools)
library(SingleCellExperiment)
```

Parameters:
```{r}
print(params)
```


# Data wrangling

## Load data, remove redundat variables
```{r, message=FALSE, warning=FALSE}
# load data
spe <- readRDS(file = "/data/pangelin/HUG/Thibaud/RC_GEOMX/data/GEO_singlecellexperiment.rds")
```

## Summary of data

```{r}
# propotion in response
table(colData(spe)$Response)
prop.table(table(colData(spe)$Response))

# are there any missing values?
any(is.na(colData(spe)$Response))
```

```{r}
if (params$usescaled) {
  assay_to_use <- 3
  assayname_to_use <- "scalelogcounts"
} else {
  assay_to_use <- 2
  assayname_to_use <- "logcounts"
}
```

## filter samples

```{r}
table(spe$batch)
```

```{r}
#spe <- spe[, !(spe$batch %in% c("GSE190826", "GSE209746","GSE45404_GPL2"))]
spe <- spe[, spe$Response %in% c("yes","no")]
dim(spe)
```

## filter features

```{r}
keep <- readRDS("/data/pangelin/HUG/Thibaud/RC_GEOMX/analysis/results/gene_lists.rds")
spe <- spe[keep[[params$gene.list]],]
dim(spe)
```


# Models


```{r}
get_model <- function(spe, folds = 5, assay_to_use=3, seed=1111){
  
  # subset predictors variables
  df_x <- t(assay(spe,assay_to_use))
  
  # subset response variable
  df_y <- spe$Response
  
  # convert diagnosis as factor
  df_y <- as.factor(df_y)
  
  print(table(df_y))

  if(folds == 1){
    set.seed(seed)
    my_trainControl <- trainControl(
      summaryFunction = twoClassSummary,
      classProbs = TRUE,
      verboseIter = FALSE,
      savePredictions = TRUE)
  } else {
    # create indices for each fold
    set.seed(seed)
    my_folds <- createFolds(df_y, k = folds)
    
    # structure of "my_fold"
    my_folds %>% glimpse
    # distribution of class is preserved in each fold
    my_folds %>% 
      map_df(~prop.table(table(df_y[.])))
    
    # create trainControl object
    my_trainControl <- trainControl(
      summaryFunction = twoClassSummary,
      classProbs = TRUE,
      verboseIter = FALSE,
      savePredictions = TRUE,
      index = my_folds)
  }
  
  # train glmnet model
  set.seed(seed+2364)
  model_glmnet <- train(x = df_x, y = df_y, 
                        method = "glmnet",
                        metric = "ROC",
                        tuneLength = 20,
                        trControl = my_trainControl, 
                        family = "binomial"
  )
  
  # print model
  model_glmnet
  
  model_glmnet$results %>% 
    as_tibble %>%  
    arrange(desc(ROC))
  
  # plot ROCs
  plot(model_glmnet)
  
  # train randomForest model
  set.seed(seed+7474)
  model_randomForest <- train(x = df_x, y = df_y, 
                              method = "ranger",
                              metric = "ROC",
                              importance = "permutation",
                              tuneLength = 20,
                              trControl = my_trainControl)
  
  # print model
  model_randomForest
  
  # plot model
  plot(model_randomForest)
  
  model_randomForest$results %>% 
    as_tibble %>%  
    arrange(desc(ROC))

  return(list(gl = model_glmnet, rf = model_randomForest))
}
```


```{r}
model_plots <- function(mymodel){
  library(plotROC)
  # Select a parameter setting
  
  selectedIndices <- !logical(length = nrow(mymodel$pred))
  for (n in names(mymodel$bestTune)) {
    print(mymodel$bestTune[[n]])
    if(is.factor(mymodel$bestTune[[n]])) mymodel$bestTune[[n]] <- as.character(mymodel$bestTune[[n]])
    selectedIndices <- selectedIndices & mymodel$pred[n] == mymodel$bestTune[[n]]
  }
  
  g <- ggplot(mymodel$pred[selectedIndices, ], aes(m=yes, d=factor(obs, levels = c("no", "yes")))) + 
    geom_roc(n.cuts=0) + 
    coord_equal() +
    style_roc()
  
  print(g + annotate("text", x=0.75, y=0.25, label=paste("AUC =", round((calc_auc(g))$AUC, 4))))
  
  print(plot(varImp(mymodel, scale = FALSE), top = 10, main = mymodel$modelInfo$label))
}
```


```{r}
predict.one <- function(mymodel, spe, assay_to_use = 3, reflevel = "yes"){
  test_res <- predict(mymodel, newdata =  t(assay(spe, assay_to_use)), type="prob")
  print(pROC::plot.roc(spe$Response, test_res$yes, print.auc=TRUE))

  test_res$obs <- ifelse(spe$Response==reflevel, 1, 0)

  g <- ggplot(test_res, aes(m=yes, d=obs)) + #factor(obs, levels = c("no", "yes"))
    geom_roc(n.cuts=0) + 
    coord_equal() +
    style_roc()
  
  
  print(g + annotate("text", x=0.75, y=0.25, label=paste("AUC =", round((calc_auc(g))$AUC, 4))))
  
  return(round((calc_auc(g))$AUC, 4))
}
```


# Loop over batches


```{r}
if(params$allds == TRUE){
  ids <- which(spe$batch %in% c(params$trainds,params$testds))
  observations <- as.factor(spe[,ids]$Response)
  set.seed(params$seed)
  train_ids <- createDataPartition(observations, times=1, p=0.7, list=FALSE)
  test_ids <- setdiff(seq(1,length(observations)), train_ids[,1])

  spe.train <- spe[, train_ids]
  cat("Train set dim:", dim(spe.train),"\n")
  
  spe.test <- spe[, test_ids]
  cat("Test set dim:", dim(spe.test),"\n")

} else {

  spe.train <- spe[, spe$batch %in% params$trainds]
  cat("Train set dim:", dim(spe.train),"\n")
  
  spe.test <- spe[, spe$batch %in% params$testds]
  cat("Test set dim:", dim(spe.test),"\n")
}
```


```{r}
res <- get_model(spe.train, folds = 1, assay_to_use = assay_to_use, seed = params$seed)
model_plots(res$gl)
model_plots(res$rf)
resamples <- resamples(res)
# plot the comparison
bwplot(resamples, metric = "ROC")
# plot the comparison per each fold
xyplot(resamples, metric = "ROC")
```

# AUC Random Forrest

```{r}
predict.one(res$rf, spe.train, assay_to_use = assay_to_use)
```

```{r}
predict.one(res$rf, spe.test, assay_to_use = assay_to_use)
```


# AUC GLMnet

```{r}
predict.one(res$gl, spe.train, assay_to_use = assay_to_use)
```

```{r}
predict.one(res$gl, spe.test, assay_to_use = assay_to_use)
```

```{r}
res <- get_model(spe, folds = 6, assay_to_use = assay_to_use, seed = params$seed)
model_plots(res$gl)
model_plots(res$rf)
```


```{r}
if(!is.null(params$save.model)){
  saveRDS(file=params$save.model, res) 
}
```
